version: '2'
services:
    web:
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8990
        volumes:
            - .:/code
        ports:
            - "8990:8990"
        depends_on:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=training.settings
    db:
        image: postgres
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
